# Base image olarak resmi Python image'ını kullan
FROM python:3.8-slim

# Çalışma dizinini ayarla
WORKDIR /app

RUN pip install requests

# Uygulama kodunu kopyala
COPY . .

# Uygulamanın çalıştırılabilir portunu belirt
EXPOSE 8000

# Uygulamayı başlat
CMD ["python", "./main.py"]